# see also: https://alacritty.org/config-alacritty.html

[env]
TERM = "xterm-256color"
TERM_PROGRAM = "alacritty"
COLORTERM = "truecolor"

[font]
size = 20.0

[[keyboard.bindings]]
action = "Paste"
key = "Y"
mods = "Control"

# Support Claude Code
[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\n"

[scrolling]
history = 0

[selection]
save_to_clipboard = true

[window]
startup_mode = "Maximized"
